# Do not under any circumstances add approvedGitRepositories to this file.
# It is a security risk that would allow arbitrary code execution both locally and in CI.
checksumBehavior: throw

defaultSemverRangePrefix: ''

enableHardenedMode: true

enableImmutableInstalls: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - '@grafana/*'

npmRegistryServer: 'https://registry.npmjs.org/'

unsafeHttpWhitelist: []

yarnPath: .yarn/releases/yarn-4.17.0.cjs
