# Do not under any circumstances add approvedGitRepositories to this file.
# It is a security risk that would allow arbitrary code execution both locally and in CI.
# https://yarnpkg.com/configuration/yarnrc#approvedGitRepositories
defaultSemverRangePrefix: ""

enableImmutableInstalls: true

enableScripts: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 4320

# Bypass minimal age gate for specific grafana packages to make feature development easier.
npmPreapprovedPackages:
  - "@grafana/*"

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.15.0.cjs
