checksumBehavior: throw

defaultSemverRangePrefix: ""

enableHardenedMode: true

enableImmutableInstalls: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - "@grafana/*"

npmRegistryServer: "https://registry.npmjs.org/"

unsafeHttpWhitelist: []

yarnPath: .yarn/releases/yarn-4.14.0.cjs
