services:
  # Grafana
  grafana:
    extends:
      file: ../../.config/docker-compose-base.yaml
      service: grafana
    volumes:
      - ../dashboards:/devenv/dashboards
      - '../datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml'
      - '../dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml'

  # Zabbix
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.4-latest@sha256:b19cfb74113012ba207c8e38ec9d62d8e09dccf620544727e4e9971d60c69973
    ports:
      - '10051:10051'
    depends_on:
      - database
    environment:
      DB_SERVER_HOST: database
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_TIMEOUT: 10
      ZBX_STARTPOLLERS: 10
      ZBX_STARTPOLLERSUNREACHABLE: 5
      ZBX_DEBUGLEVEL: 3

  zabbix-web:
    image: zabbix/zabbix-web-apache-pgsql:alpine-7.4-latest@sha256:78fcb97240775265a52de2071a12b96a5c0f36499cd37010a38d41c418880e0d
    ports:
      - '8188:8080'
    depends_on:
      - database
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      DB_SERVER_HOST: database
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix

  database:
    image: postgres:18@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    ports:
      - '15432:5432'
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.4-latest@sha256:8479653c202f4a87f992d50343f4763477a853dab088a568dd654c2d10997316
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051

  #########################################################
  # Bootstrap config
  #########################################################

  bootstrap:
    build: ./bootstrap
    environment:
      ZBX_API_URL: http://zabbix-web:8080
      ZBX_API_USER: Admin
      ZBX_API_PASSWORD: zabbix
    depends_on:
      - database
      - zabbix-server
      - zabbix-web

  #########################################################
  # Fake agents
  #########################################################

  # backend
  redis_backend:
    image: redis:alpine@sha256:c5e375abb885e6b2021c0377879e4890bf76f9065b8922ffc113f2b226b9fc17

  zas_backend_01:
    build: ../zas-agent
    volumes:
      - ../zas-agent/conf/zas_scenario_backend.cfg:/etc/zas_scenario.cfg
    environment:
      REDIS_HOST: redis_backend
    # restart: always

  zas_backend_02:
    build: ../zas-agent
    volumes:
      - ../zas-agent/conf/zas_scenario_backend.cfg:/etc/zas_scenario.cfg
    environment:
      REDIS_HOST: redis_backend

  # frontend
  redis_frontend:
    image: redis:alpine@sha256:c5e375abb885e6b2021c0377879e4890bf76f9065b8922ffc113f2b226b9fc17

  zas_frontend_01:
    build: ../zas-agent
    volumes:
      - ../zas-agent/conf/zas_scenario_frontend.cfg:/etc/zas_scenario.cfg
    environment:
      REDIS_HOST: redis_frontend

  zas_frontend_02:
    build: ../zas-agent
    volumes:
      - ../zas-agent/conf/zas_scenario_frontend.cfg:/etc/zas_scenario.cfg
    environment:
      REDIS_HOST: redis_frontend