services:
  # Grafana
  grafana:
    extends:
      file: ../../.config/docker-compose-base.yaml
      service: grafana
    volumes:
      - ../..:/grafana-zabbix
      - ../dashboards:/devenv/dashboards
      - '../datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml'
      - '../dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml'

  # Zabbix
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.2-latest@sha256:f600fb6abf7dd4c7ddbc7dfcafb3a9695e0c50b0b2f44e51c93852510a7dfa1d
    ports:
      - '10051:10051'
    depends_on:
      - database
    environment:
      DB_SERVER_HOST: database
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_TIMEOUT: 10
      ZBX_STARTPOLLERS: 10
      ZBX_STARTPOLLERSUNREACHABLE: 5
      ZBX_DEBUGLEVEL: 3

  zabbix-web:
    image: zabbix/zabbix-web-apache-pgsql:alpine-7.2-latest@sha256:f47fcc49afdcf0fb9cb73605d4113b1810ad0b4c46ff04f37e649cf9a142c2d8
    ports:
      - '8188:8080'
    depends_on:
      - database
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      DB_SERVER_HOST: database
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix

  database:
    image: postgres:16@sha256:74bbe2dbc3c388b05544576167540fc5d8557017282b1c889344137ea7160061
    ports:
      - '15432:5432'
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.2-latest@sha256:2686dc601fb1ba257eceb042b79329dd2be8e8d18de4d66f8b08f77e1a6b433f
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051

  #########################################################
  # Bootstrap config
  #########################################################

  bootstrap:
    build: ./bootstrap
    environment:
      ZBX_API_URL: http://zabbix-web:8080
      ZBX_API_USER: Admin
      ZBX_API_PASSWORD: zabbix
    depends_on:
      - database
      - zabbix-server
      - zabbix-web

  #########################################################
  # Fake agents
  #########################################################

  # backend
  redis_backend:
    image: redis:alpine@sha256:28c9c4d7596949a24b183eaaab6455f8e5d55ecbf72d02ff5e2c17fe72671d31

  zas_backend_01:
    build: ../zas-agent
    volumes:
      - ../zas-agent/conf/zas_scenario_backend.cfg:/etc/zas_scenario.cfg
    environment:
      REDIS_HOST: redis_backend
    # restart: always

  zas_backend_02:
    build: ../zas-agent
    volumes:
      - ../zas-agent/conf/zas_scenario_backend.cfg:/etc/zas_scenario.cfg
    environment:
      REDIS_HOST: redis_backend

  # frontend
  redis_frontend:
    image: redis:alpine@sha256:28c9c4d7596949a24b183eaaab6455f8e5d55ecbf72d02ff5e2c17fe72671d31

  zas_frontend_01:
    build: ../zas-agent
    volumes:
      - ../zas-agent/conf/zas_scenario_frontend.cfg:/etc/zas_scenario.cfg
    environment:
      REDIS_HOST: redis_frontend

  zas_frontend_02:
    build: ../zas-agent
    volumes:
      - ../zas-agent/conf/zas_scenario_frontend.cfg:/etc/zas_scenario.cfg
    environment:
      REDIS_HOST: redis_frontend
