name: Add issues to Data Source Plugin team project
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    permissions:
      contents: read
      id-token: write
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - id: get-github-token
        uses: grafana/shared-workflows/actions/create-github-app-token@46f48da11e78ebdba7a8747ae456b11062fac83e # create-github-app-token/v0.3.1
        with:
          github_app: grafana-oss-big-tent
      - name: Add to project
        uses: actions/add-to-project@00a39cd6fa0633a59f7ae3bd4edada12a688183f # main
        with:
          project-url: https://github.com/orgs/grafana/projects/1085
          github-token: ${{ steps.get-github-token.outputs.token }}
