name: Add issues & PRs to Grafana Data Source Plugins Squad project
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    permissions:
      contents: read
      id-token: write
    uses: grafana/data-sources-ci-workflows/.github/workflows/reusable-add-to-project.yml@main # zizmor: ignore[unpinned-uses]
