name: Compatibility check
on: [push]

jobs:
  compatibilitycheck:
    permissions:
      # Required permissions when comment-pr is set to 'yes': pull-requests: write, contents: read
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build plugin
        run: yarn build
      - name: Compatibility check
        uses: grafana/plugin-actions/is-compatible@main
        with:
          module: './src/module.ts'
          comment-pr: 'yes'
          fail-if-incompatible: 'no'
